version: "3" # Use Docker Compose version 3

services:
  ghost:
    image: ghost:latest # Use the Ghost Docker image 	linux/arm64/v8?
    restart: always
    ports:
      - 8080:2368 
    environment:
      - NODE_ENV=development
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=portainer
      - database__connection__database=ghost
      - url=url: http://localhost:8080:2368 # Set the base URL for the Ghost application
    volumes:
      - ghost-content:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_USER=ghost
      - MYSQL_DATABASE=ghost
      - MYSQL_PASSWORD=portainer
      - MARIADB_ROOT_PASSWORD=portainer
    volumes:
      - mariadb-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  ghost-content:
  mariadb-data:
