version: "3" # Use Docker Compose version 3

services:
  ghost:
    image: ghost:latest # Use the Ghost Docker image 	linux/arm64/v8?
    restart: always 
    environment:
      - NODE_ENV=development
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=portainer
      - database__connection__database=ghost
      - url=http://[YOUR_IP]:2368 # Set the base URL for the Ghost application
    volumes:
      - ghost-content:/var/lib/ghost/content
    ports:
      - "2368:2368" # Map port 2368 from the host to port 2368 in the container
    depends_on:
      - db

  db:
    image: mysql:8.0 # Use the MySQL Docker image
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql # Mount a volume for persistent MySQL data storage
    environment:
      - MYSQL_USER=ghost # Set the MySQL user
      - MYSQL_DATABASE=ghost # Set the MySQL database name
      - MYSQL_PASSWORD=portainer # Set the MySQL user's password
      - MYSQL_ROOT_PASSWORD=portainer # Set the MySQL root password

volumes:
  ghost-content:
  mysql-data:
